snmptrap_snmpuser_binding: add check for resource
citrix/adc-nitro-go pull request #38
Opened 2022-08-31 10:26 UTC by ChrisM3rsi

Signed-off-by: christosm <christos.mersinis@citrix.com>

2022-09-07 08:45 UTC, sumanth-lingappa requested changes

2022-09-07 08:45 UTC, sumanth-lingappa commented on service/config.go
> +		get_args := args[:len(args)-1]
Please iterate over the `args` array and remove the item with the `username` key.

2022-09-08 07:33 UTC, sumanth-lingappa requested changes

2022-09-08 07:33 UTC, sumanth-lingappa commented on service/config.go
> +	//Remove unwanted argument (username) for listing but keep it for delete operation
this comment should come inside the `if` block

2022-09-08 07:33 UTC, sumanth-lingappa commented on service/config.go
> +		get_args := make([]string, 0)
rename `get_args` to a meaningful variable name. eg., `argsWithoutUsername`

2022-09-08 07:33 UTC, sumanth-lingappa commented on service/config.go
> +				//append all elements except username
This comment is not required. Your code explains it.
Maybe you can explain the intention behind it. Not what your code is doing.

2022-09-09 06:40 UTC, sumanth-lingappa approved these changes

2022-09-09 06:40 UTC, merged

2022-09-09 07:23 UTC, imkritesh commented
Hello @sumanth-lingappa @ChrisM3rsi ,

I wanted to get context on why do we need to remove username parameter for snmptrap_snmpuser_binding  while doing get request ?